### PR TITLE
auto step when long press

### LINKED ISSUE #15: mousedown on steps should step
mousedown on steps should step. This mean you can go up and down in value with a continuous press like it works with the arrow keybindings.

Currently it just does it in the case of "onClick"

### PR DESCRIPTION
**Pull request by afc163**
will close #15 and https://github.com/ant-design/ant-design-mobile/issues/91

---

native 的不知道怎么调试，@silentcloud 来同步改下。

> 好像有个 onLongPress 可以用。

### CODE REVIEW

**Comment by yiminghe** [comment]
@silentcloud review 看下 rn 有没问题

**Comment by afc163** [comment]
ping

**Comment by warmhug** [comment]
能否合并到 0.8 ？

**Comment by silentcloud** [comment]
没注意，我这会看看 rn

**Comment by hfiguiere** [comment]
the auto step seems to trigger quite quickly. so quickly that step by step is almost impossible (this is the web React component, not React Native)

**Comment by hfiguiere** [comment]
also:
-mouse down on the stop buttons. 
-mouve the mouse out of the control
-release the button.

the stepper still goes on.

**Pull request merged**
