### PR TITLE
Fix type definition of ValueType and InputNumber onChange

### LINKED ISSUE #481: Type of `ValueType` is incorrect - is `string | number | null`, should be `string | number`
`null` was added to resolve https://github.com/ant-design/ant-design/issues/37412 - however, the fix in #470 was incorrect. Having `null` as a valid value for all `ValueType` entries breaks compatibility with `React.InputHTMLAttributes` `min`, `max`, and `step` properties which explicitly exclude null. This is preventing this library from being used in projects with strict null checks enabled.

The correct solution here is to add `null` to the input value type of the `onChange` function, and nowhere else. It is explicitly called with `null` only in one special case as outlined in https://github.com/react-component/input-number/blob/master/src/InputNumber.tsx#L313

### PR DESCRIPTION
**Pull request by fnimick**
Resolves #481

### CODE REVIEW

**Comment by afc163** [comment]
@li-jia-nan

**Comment by li-jia-nan** [comment]
> @li-jia-nan

好像没问题，我上周也打算把这个 ValueType 中的null去掉~~

**Comment by zombieJ** [comment]
This breaks control usage:
截屏2022-09-19 15 32 55

截屏2022-09-19 15 33 12

`value` & `onChange` should both support `null` or both not support `null`.

**Comment by li-jia-nan** [comment]
> This breaks control usage: 截屏2022-09-19 15 32 55
> 
> 截屏2022-09-19 15 33 12
> 
> `value` & `onChange` should both support `null` or both not support `null`.

- #483

**Pull request merged**
