### PR TITLE
[fixed] format input cursor position

### PR DESCRIPTION
**Pull request by 120216220**
fixed InputNumber cursor position disorder when using format  [#98](https://github.com/react-component/input-number/issues/98) [#10756](https://github.com/ant-design/ant-design/issues/10756)

### CODE REVIEW

**Comment by afc163** [comment]
This will break the second demo in http://react-component.github.io/input-number/examples/formatter.html

https://github.com/ant-design/ant-design/issues/10722

**Comment by 120216220** [comment]
One needs to correct the offset, one does not, I can't find a better way for now

**Comment by chenhaizhou** [comment]
so, are you not planning to fix this issue?

**Comment by 120216220** [comment]
@chenhaizhou  我公司我现在还是采用这个方案，再进行了一点优化，同时让业务方在使用上去规避这种问题。组件利用正则format，我暂时是想不出一个更好的阻止光标混乱的方案。

**Comment by afc163** [comment]
https://github.com/react-component/input-number/commit/17a56fa1ae437ac701c2676585a207e7fa10448f

**Comment by 120216220** [comment]
@afc163 http://react-component.github.io/input-number/examples/formatter.html The first demo still has problem，the defaultValue is 1000. you will see that the cursor is not behind the last 2 when you enter 222 behind 1.

**Comment by afc163** [comment]
@120216220 Right, it is almost impossible to get a perfect correct cursor position when it is in the middle of value.

**Comment by 120216220** [comment]
@afc163 I think so, too. Thank you

**Comment by chenhaizhou** [comment]
@120216220 我看到最新的rc-input-number已经修复了，但是如果不用defaultValue设置默认值，直接使用value，光标的问题还是依旧存在。

**Comment by 120216220** [comment]
@chenhaizhou 不好意思，暂时没在关注这个问题了，业务繁忙。偏右大神在上面也说了，几乎不可能找到完美的光标定位解决方案。我认为你要嘛规避这个问题，要嘛基于你们自身的业务逻辑去修改源码。

**Comment by afc163** [comment]
@chenhaizhou 受控组件有问题的话，不妨提一个新的 issue：http://new-issue.ant.design/

**Comment by chenhaizhou** [comment]
已提交 https://github.com/ant-design/ant-design/issues/11071

**Pull request closed without merging**
