### PR TITLE
change default to max safe integer

### LINKED ISSUE #69: Change Max Number to Number.MAX_SAFE_NUMBER
By default, I don't think the max number should be `Infinity`, as javascript will basically not handle numbers above [The Max Safe Integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). This results in unpredictable behavior in large numbers in this component. Conversely, we should probably change the default minimum to `- MAX_SAFE_INTEGER`

If you're okay with this change I'll PR.

### PR DESCRIPTION
**Pull request by alexggordon**
This fixes #69

### CODE REVIEW

**Comment by alexggordon** [comment]
@paranoidjk do you know why the CI failed here?

**Comment by paranoidjk** [comment]
@alexggordon can you try restart build?

**Comment by paranoidjk** [comment]
@afc163 #35 的用例超时了，估计是700次循环的原因，默认是  2000ms 超时

**Comment by alexggordon** [comment]
@paranoidjk looks like this is an intermittent. it times out about 50% of the time. It does it on earlier commits too.

**Comment by paranoidjk** [comment]
@alexggordon Published `rc-input-number@3.6.1`

**Pull request merged**
