### PR TITLE
Add step to the input attributes

### PR DESCRIPTION
**Pull request by jpagand**
Step must be added to the input attributes in order to avoid native validation error when min is used.

To reproduce:

``` 
       <InputNumber
          min={0.5}
          step={0.5}
        />
```
and try to submit an integer

### CODE REVIEW

**Comment by paranoidjk** [comment]
I think step by default will be 1? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Controlling_step_size

**Comment by jpagand** [comment]
Indeed the step is 1 by default but if I set him to 0.5, I want him to be 0.5 ;)

**Comment by jpagand** [comment]
any news?

**Comment by afc163** [comment]
What the problem does this PR mean to resolve?

**Comment by paranoidjk** [comment]
@jpagand I can not reproduce your problem.

**Comment by benjycui** [comment]
@jpagand do you mean this?

image

**Comment by benjycui** [comment]
@jpagand and you should not commit `es` directory, please remove it.

**Comment by jpagand** [comment]
@benjycui I totally mean this

**Pull request merged**
