### PR TITLE
Add decimal separator prop

### PR DESCRIPTION
**Pull request by amedora**
This PR is a revised one of #112

### CODE REVIEW

**Comment by zombieJ** [comment]
In which case need this feature?

**Comment by amedora** [comment]
@zombieJ 
Some countries & regions use comma instead of dot as decimal separator.
See #104

**Comment by zombieJ** [comment]
Thanks. Name `separator` of prop may makes user confuse. We'd better use other name instead.
Maybe `decimalSeparator` or something else?

How do you think about this? @amedora @afc163 @yesmeck

**Comment by amedora** [comment]
looks ok.
I'm ready to commit & push that change.

**Pull request merged**
